spring.application.name=accountmicroservice

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/fincore_account
spring.datasource.username=root
spring.datasource.password=harini@232007

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
