spring.application.name=LOAN-SERVICE
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/fincore_loan?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=harini@232007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ACCOUNT SERVICE
account.service.url=http://localhost:8082
